sizeRow: 100
sizeColumn: 20
###############################
probabilityOfEating:
  wolf:
    wolf: 0         #      Волк
    boa: 0          #      Удав
    fox: 0          #      Лиса
    bear: 0           #      Медведь
    eagle: 0         #      Орел
    horse: 10         #      Лошадь
    deer: 15          #      Олень
    rabbit: 60        #      Кролик
    mouse: 80         #      Мышь
    goat: 60          #      Коза
    sheep: 70         #      Овца
    boar: 15           #      Кабан
    buffalo: 10        #      Буйвол
    duck: 40          #      Утка
    caterpillar: 0    #      Гусеница
    plants: 0         #      Растения
  boa:
    wolf: 0
    boa: 0
    fox: 15
    bear: 0
    eagle: 0
    horse: 0
    deer: 0
    rabbit: 20
    mouse: 40
    goat: 0
    sheep: 0
    boar: 0
    buffalo: 0
    duck: 10
    caterpillar: 0
    plants: 0
  fox:
    wolf: 0
    boa: 0
    fox: 0
    bear: 0
    eagle: 0
    horse: 0
    deer: 0
    rabbit: 70
    mouse: 90
    goat: 0
    sheep: 0
    boar: 0
    buffalo: 0
    duck: 60
    caterpillar: 40
    plants: 0
  bear:
    wolf: 0
    boa: 80
    fox: 0
    bear: 0
    eagle: 0
    horse: 40
    deer: 80
    rabbit: 80
    mouse: 90
    goat: 70
    sheep: 70
    boar: 50
    buffalo: 20
    duck: 10
    caterpillar: 0
    plants: 0
  eagle:
    wolf: 0
    boa: 0
    fox: 10
    bear: 0
    eagle: 0
    horse: 0
    deer: 0
    rabbit: 90
    mouse: 90
    goat: 0
    sheep: 0
    boar: 0
    buffalo: 0
    duck: 80
    caterpillar: 0
    plants: 0
  horse:
    wolf: 0
    boa: 0
    fox: 0
    bear: 0
    eagle: 0
    horse: 0
    deer: 0
    rabbit: 0
    mouse: 0
    goat: 0
    sheep: 0
    boar: 0
    buffalo: 0
    duck: 0
    caterpillar: 0
    plants: 100
  deer:
    wolf: 0
    boa: 0
    fox: 0
    bear: 0
    eagle: 0
    horse: 0
    deer: 0
    rabbit: 0
    mouse: 0
    goat: 0
    sheep: 0
    boar: 0
    buffalo: 0
    duck: 0
    caterpillar: 0
    plants: 100
  rabbit:
    wolf: 0
    boa: 0
    fox: 0
    bear: 0
    eagle: 0
    horse: 0
    deer: 0
    rabbit: 0
    mouse: 0
    goat: 0
    sheep: 0
    boar: 0
    buffalo: 0
    duck: 0
    caterpillar: 0
    plants: 100
  mouse:
    wolf: 0
    boa: 0
    fox: 0
    bear: 0
    eagle: 0
    horse: 0
    deer: 0
    rabbit: 0
    mouse: 0
    goat: 0
    sheep: 0
    boar: 0
    buffalo: 0
    duck: 0
    caterpillar: 90
    plants: 100
  goat:
    wolf: 0
    boa: 0
    fox: 0
    bear: 0
    eagle: 0
    horse: 0
    deer: 0
    rabbit: 0
    mouse: 0
    goat: 0
    sheep: 0
    boar: 0
    buffalo: 0
    duck: 0
    caterpillar: 0
    plants: 100
  sheep:
    wolf: 0
    boa: 0
    fox: 0
    bear: 0
    eagle: 0
    horse: 0
    deer: 0
    rabbit: 0
    mouse: 0
    goat: 0
    sheep: 0
    boar: 0
    buffalo: 0
    duck: 0
    caterpillar: 0
    plants: 100
  boar:
    wolf: 0
    boa: 0
    fox: 0
    bear: 0
    eagle: 0
    horse: 0
    deer: 0
    rabbit: 0
    mouse: 50
    goat: 0
    sheep: 0
    boar: 0
    buffalo: 0
    duck: 0
    caterpillar: 90
    plants: 100
  buffalo:
    wolf: 0
    boa: 0
    fox: 0
    bear: 0
    eagle: 0
    horse: 0
    deer: 0
    rabbit: 0
    mouse: 50
    goat: 0
    sheep: 0
    boar: 0
    buffalo: 0
    duck: 0
    caterpillar: 0
    plants: 100
  duck:
    wolf: 0
    boa: 0
    fox: 0
    bear: 0
    eagle: 0
    horse: 0
    deer: 0
    rabbit: 0
    mouse: 50
    goat: 0
    sheep: 0
    boar: 0
    buffalo: 0
    duck: 0
    caterpillar: 90
    plants: 100
  caterpillar:
    wolf: 0
    boa: 0
    fox: 0
    bear: 0
    eagle: 0
    horse: 0
    deer: 0
    rabbit: 0
    mouse: 0
    goat: 0
    sheep: 0
    boar: 0
    buffalo: 0
    duck: 0
    caterpillar: 0
    plants: 100
#######################################
entityProperty:
  wolf:
    weight: 50          #вес одного животного
    maxPopulation: 30   #Максимальное количество животных этого вида на одной клетке
    speed: 3            #Скорость перемещения, не более чем, клеток за ход
    food: 8             #Сколько килограммов пищи нужно животному для полного насыщения
  boa:
    weight: 15
    maxPopulation: 30
    speed: 1
    food: 3
  fox:
    weight: 8
    maxPopulation: 30
    speed: 2
    food: 2
  bear:
    weight: 500
    maxPopulation: 5
    speed: 2
    food: 80
  eagle:
    weight: 6
    maxPopulation: 20
    speed: 3
    food: 1
  horse:
    weight: 400
    maxPopulation: 20
    speed: 4
    food: 60
  deer:
    weight: 300
    maxPopulation: 20
    speed: 4
    food: 50
  rabbit:
    weight: 2
    maxPopulation: 150
    speed: 2
    food: 0.45
  mouse:
    weight: 0.05
    maxPopulation: 500
    speed: 1
    food: 0.01
  goat:
    weight: 60
    maxPopulation: 140
    speed: 3
    food: 10
  sheep:
    weight: 70
    maxPopulation: 140
    speed: 3
    food: 15
  boar:
    weight: 400
    maxPopulation: 50
    speed: 2
    food: 50
  buffalo:
    weight: 700
    maxPopulation: 10
    speed: 3
    food: 100
  duck:
    weight: 1
    maxPopulation: 200
    speed: 4
    food: 0.15
  caterpillar:
    weight: 0.01
    maxPopulation: 1000
    speed:
    food: 0
  plant:
    weight: 1
    maxPopulation: 2000